---
  .travis.yml:
    hc_secure: "aWQzE9dBdTs2zGrCq8q13FYrB9KuNtJQ0VlWcJVOEf+6qhwWPMu5aKwYKZQcrIswFxGHytIjPuvNf8AAHzfXvtFHPWSURnrRDISlXiCha+B4Opf3BhDFEzK2H7c5JMXhyzYxZJ8iKzBMWipr9UGWm+VsoWLSKsan4qlLcb+V2Gc="

